build.gradle
src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
src/test/resources/application.yml

close: #12 
> main과 test의 application.yml 파일을 DB 관련 설정을 상황에 맞게 세팅하기 위함
- 실제 서비스 DB URL을 기존 URL에서 db이름까지 환경변수로 받음
- 테스트는 기본 h2 인메모리 db를 사용
- MemberControllerTest파일에서 실패하는 코드 수정

[setting] application.yml 파일에서 DB 관련 설정 변경

---

build.gradle
src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
src/main/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepository.java
src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
src/main/java/com/kernel360/kernelsquare/domain/question/controller/QuestionController.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/PutQuestionRequest.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
src/main/java/com/kernel360/kernelsquare/domain/question/entity/Question.java
src/main/java/com/kernel360/kernelsquare/domain/question/repository/QuestionRepository.java
src/main/java/com/kernel360/kernelsquare/domain/question/service/QuestionService.java
src/main/java/com/kernel360/kernelsquare/domain/question_tech_stack/entity/QuestionTechStack.java
src/main/java/com/kernel360/kernelsquare/domain/question_tech_stack/repository/QuestionTechStackRepository.java
src/main/java/com/kernel360/kernelsquare/domain/rank/entity/Rank.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepository.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/QuestionErrorCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/QuestionResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/QuestionServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/dto/PageResponse.java
src/main/java/com/kernel360/kernelsquare/global/dto/Pagination.java
src/main/resources/data.sql
src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
src/test/java/com/kernel360/kernelsquare/domain/question/controller/QuestionControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
src/test/resources/application.yml

close: #5 
> QnA 중 질문의 기본적인 CRUD 기능을 구현하기 위함
- API 명세서와 ERD 기준으로 CRUD를 위한 코드 작성과 함께 약간의 코드 리팩토링 진행
- 테스트는 서비스와 컨트롤러 정상 동작에 대한 것만 작성(에러 상황에 대한 테스트 x)
- 이 후, 코드 품질이나 다른 도메인 기능 개발에 따른 리팩토링이 필요한 부분은 있음
- 기능 구현을 위해 다른 도메인이지만 필요한 코드 또는 파일 추가
- data.sql을 통해 기능 동작 확인을 위한 최소한의 데이터를 넣음
- 이 data.sql은 테스트를 할 때 실행시키지 않기 위해 test.resources에 테스트용 application.yml 파일 추가

[feat] 질문 기능 개발

---

src/main/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerController.java
src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAnswerResponse.java
src/main/java/com/kernel360/kernelsquare/domain/answer/entity/Answer.java
src/main/java/com/kernel360/kernelsquare/domain/answer/repository/AnswerRepository.java
src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/AnswerResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/QuestionResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java

체크박스 Close : #14 에서 해당 질문에 대한 모든 답변 조회에 해당하는 기능
> 기능 추가를 위한 Answer 도메인 기능 개발
> 서비스 상태 ENUM TYPE으로 정의 & 명세서 작성(https://www.notion.so/c54aec9cd60e47078d0d321b0472ae09)
> 해당 기능에 대한 테스트 코드 작성 및 동작 확인
- 리포지토리는 Answer 리스트를 반환
- 서비스는 DTO 매핑
- Rank 부분은 우선 하드코딩
- 컨트롤러 API 명세대로 작동 (Talend API에서 확인됨)

[feat] 단일 질문에 대한 복수 답변 조회 기능

---

build.gradle
src/main/java/com/kernel360/kernelsquare/global/aop/Logging.java
src/main/resources/logback.xml

close: #16 
> 필요한 로그를 파일로 남기기 위함
- 현재 logback.xml 파일에 로그에 대한 모든 설정을 넣어둠
- 현재 Member와 Quesiton의 모든 서비스 메서드 시작, 종료, 걸린 시간과 JPA 걸린 시간을 남김
- 서비스 메서드 시작은 Start 패키지명, 클래스명, 메서드명을 나타냅니다.
- 서비스 종료는 클래스명.메서드, 걸린시간을 나타냅니다.
- 서비스 에러는 클래스명.메서드, 캐치한 에러를 나타냅니다.
- JPA는 클래스명(현재는 전부 CrudRepository).메서드, 걸린시간을 나타냅니다.
- 로그 정책이 정해지면 리팩토링이 필수

[feat] 로그 AOP 1차 완성

---

src/main/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepository.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
src/test/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepositoryTest.java

close: #52 
> 이미 존재하는 기술 스택으로 수정하려고 할 때의 예외 처리를 구현하기 위함
- TechStackRepository에 기술 스택이 존재하는지 확인하는데 existsBySkill메서드를 추가
- existsBySkill가 true면 커스텀 예외 발생 시키고 그렇지 않다면 update를 함
- 추가적으로 서비스 부분에서 수정과 삭제의 코드 순서를 바꿈

[refactor] 기술 스택 수정 서비스 로직에 예외 처리 로직 추가

---

src/main/java/com/kernel360/kernelsquare/domain/member/dto/FindMemberResponse.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/main/resources/data.sql
src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java

close: #79 
> 현재 정책 상 풀 URL로 응답을 보내고 있기 때문에, 풀 URL로 보내도록 고치기 위함
- findQuestionResponse와 findMemberResponse 이미지 URL 부분 수정
- 추가적으로 data.sql 수정

[bugfix] 이미지 URL 응답을 s3 주소가 빠진 상태로 보내는 문제

---

.github/workflows/gradle.yml
src/main/java/com/kernel360/kernelsquare/domain/auth/controller/AuthController.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateEmailRequest.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateNicknameRequest.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginRequest.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginResponse.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/SignUpRequest.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/TokenRequest.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/TokenResponse.java
src/main/java/com/kernel360/kernelsquare/domain/auth/service/AuthService.java
src/main/java/com/kernel360/kernelsquare/domain/authority/entity/Authority.java
src/main/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepository.java
src/main/java/com/kernel360/kernelsquare/global/jwt/TokenProvider.java
src/test/java/com/kernel360/kernelsquare/domain/auth/controller/AuthControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/auth/service/AuthServiceTest.java
src/test/java/com/kernel360/kernelsquare/domain/auth/service/MemberDetailServiceTest.java
src/test/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepositoryTest.java
src/test/java/com/kernel360/kernelsquare/global/jwt/TokenProviderTest.java
src/test/resources/application.yml

close: #100 #96 
- 인증 관련된 테스트들이 작성되어 있지 않아 새로 추가하였습니다.
- 인증 관련된 서비스와 컨트롤러 내부 로직을 리팩토링하여 하나의 서비스에 너무 많은 책임이 몰려 있지 않도록 했습니다.
- 그 외 서비스 내부도 리팩토링하여 불필요한 라인들을 삭제하고 하나의 메서드에 남도록 하였습니다.
- 기존에 ``AssertThatThrownBy``를 사용하면 내부 값을 테스트 할 수 없었던 경우를 이번 테스트에 새로이 알게된 ``extracting``을 통해 내부 에러코드 또한 확인할 수 있도록 하였습니다.
- RefreshToken이 인코딩 되지 않고 클라이언트에 보내지던 현상을 막았습니다.
- 그와 관련하여 내부의 토큰이 제대로 동작하는지 확인하기 위해 각 서비스와 컨트롤러에 대한 테스트를 작성하였습니다.
- 이외에 TokenDTO를 응답과 요청 DTO로 분리하였습니다

[refactor] AuthController 내부 서비스 분리 및 인증 관련 테스트 작성, Auth 관련 클래스 리팩토링

---

src/main/java/com/kernel360/kernelsquare/domain/authority/entity/Authority.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/entity/HashTag.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/repository/HashTagRepository.java
src/main/java/com/kernel360/kernelsquare/domain/reservation/entity/Reservation.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticle.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleController.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/CreateReservationArticleRequest.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/CreateReservationArticleResponse.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/entity/ReservationArticle.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/repository/ReservationArticleRepository.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/ReservationArticleResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/ReservationArticleServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/main/resources/application.yml
src/main/resources/data.sql
src/test/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java

close: #85 
> 커피챗 예약 게시글 생성
- 예약 게시글 엔티티, 예약 엔티티, 해시태그 엔티티 생성
- 예약 게시글 서비스, 컨트롤러 Create 생성
- data.sql 에 멘토 추가
- SecurityConfig 에 멘토 permitAll, hasRole 추가
- 테스트 코드 작성

[feat] 커피챗 예약 게시글 생성

---

src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginResponse.java

close: #108 
> 프론트가 이해할 수 있는 문자열 형태로 보내주도록 하기 위함
- Authoriy객체 주소에서 Authoriy의 AuthorityType의 문자열을 보내주도록 LoginResponse 수정
- 추가적으로 member의 image_url을 절대 URL로 보내주도록 LoginResponse 수정

[bugfix] 로그인 응답 ROLE 정상적으로 보내주도록 LoginResponse 수정

---

src/main/java/com/kernel360/kernelsquare/domain/reservation/dto/ReservationDto.java
src/main/java/com/kernel360/kernelsquare/domain/reservation/entity/Reservation.java
src/main/java/com/kernel360/kernelsquare/domain/reservation/repository/ReservationRepository.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleController.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindAllReservationArticleResponse.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindReservationArticleResponse.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/entity/ReservationArticle.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/ReservationArticleErrorCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/ReservationArticleResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/ReservationArticleServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/main/resources/db/migration/V1.2__add_initial_data.sql
src/test/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java

close: #84 
> 커피챗 - 예약창 생성
- 모든 예약창 조회 기능 구현
- 예약창 상세 조회 기능 구현
- 테스트 코드 작성
- 예약내역 DTO
- 모든 예약창 응답에는 예약 남은 자리가 몇자리 남았는지 fullCheck 으로 전달
- FOUNDED, NOT FOUND, NOT PAGE 예외 응답코드 작성

[feat] 커피챗 - 예약창 조회

---

src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindAllReservationArticleResponse.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindReservationArticleResponse.java

> 예약창 전체조회, 상세조회 시 해시태그 응답값 버그 수정
- 해시태그가 주소값으로 나와 코드 수정하여 문자로 나오게 수정

[fix] 예약창 전체조회, 상세조회 시 해시태그 응답값 버그 수정

---

src/main/resources/db/migration/V1.4__alter_table.sql

close: #138 
> image_url이 길어서 DB에 저장이 안되는 문제를 varchar 길이 제한을 늘려 해결하기 위함
- 기존 sql 파일을 수정하는 것이 아닌, flyway 버전 업을 통해 변경
- question, answer, member, answer_rank, level 테이블의 image_url 컬럼의 속성을 varchar(100)에서 varchar(200)으로 변경

[bugfix] image_url 컬럼들 varchar(100)에서 varchar(200)으로 변경

---

src/main/java/com/kernel360/kernelsquare/domain/hashtag/controller/HashtagController.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/FindAllHashtagResponse.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/FindHashtagResponse.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/HashtagResponse.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/entity/Hashtag.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/repository/HashtagRepository.java
src/main/java/com/kernel360/kernelsquare/domain/hashtag/service/HashtagService.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindAllReservationArticleResponse.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindReservationArticleResponse.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/entity/ReservationArticle.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/HashTagResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/HashTagServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/test/java/com/kernel360/kernelsquare/domain/hashtag/controller/HashtagControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/hashtag/service/HashtagServiceTest.java
src/test/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java

close: #136 #137 #135 
> 해시태그 조회와 삭제 기능 구현
- 해시태그 모든 조회 기능 구현
- 해시태그 삭제 기능 구현
- HashTag 로 되어있던 부분들 -> Hashtag 로 수정
- ~순환참조 방지를 위해 @JsonIgnore 달음~  -> 다시 지우고 DTO 로 Response 만들어서 순환참조 방지함
- 테스트 완료

[feat] 해시태그 조회, 삭제 기능 구현

---

src/main/java/com/kernel360/kernelsquare/domain/search/controller/SearchController.java
src/main/java/com/kernel360/kernelsquare/domain/search/dto/SearchQuestionResponse.java
src/main/java/com/kernel360/kernelsquare/domain/search/service/SearchService.java
src/test/java/com/kernel360/kernelsquare/domain/search/controller/SearchControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/search/service/SearchServiceTest.java

close: #143 
> 질문 목록 검색에서 검색된 총 질문 수도 포함해서 응답으로 보내주기 위함
- 검색된 질문의 총개수 totalCount 추가
- list -> question_list로 응답 값 변경

[refactor] 질문 검색 응답 dto 변경

---

src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java

close: #146 
> 회원 이미지 변경할 때, 이미지 URL이 정상적으로 처리가 되지 않는 문제를 해결하기 위함
- memberService 파일에서 updateMemberRequest에서 받은 imageUrl을 처리하고 update를 하도록 수정

[bugfix] 회원 이미지 수정시 정상적으로 이미지 URL 처리 로직 추가

---

src/main/java/com/kernel360/kernelsquare/domain/member/controller/MemberController.java
src/main/java/com/kernel360/kernelsquare/domain/member/dto/FindMemberResponse.java
src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberIntroductionRequest.java
src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberProfileRequest.java
src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/MemberResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AuthorityServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CommonServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/MemberAnswerVoteStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/MemberServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TokenServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/config/CorsConfig.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java

close: #158 
> 회원 소개 변경 시 프로필이 Null로 바뀌는 버그 수정
> API를 분리하여 관련 문제가 없도록 만듬
> 이슈에 관련된 설명
- 회원 정보 수정을 회원 프로필 수정과 회원 소개 수정으로 바꾸고 응답 상태 코드를 업데이트
- 소개변경 API : member/{memberId}/introduction
- 프로필변경 API : member/{memberId}/profile
- API 명세서
- https://www.notion.so/API-0dd89c67c2af4c2abedcc4712f8e627e
- 응답상태코드
- https://www.notion.so/c54aec9cd60e47078d0d321b0472ae09

[bugfix] 회원 정보 수정 API 분리

---

member-api/src/main/java/com/kernelsquare/memberapi/common/util/ChatMessageConverter.java
member-api/src/main/resources/application.yml
member-api/src/main/resources/templates/chat/screen.html

close: #182 
> member-api를 실행하여 채팅했을 때 몽고db에 저장되지 않는 문제를 해결하기 위함
- member-api application.yml에 몽고db uri가 있어야 동작함
- 추가적으로 MongoChatMessage로 컨버터할 때 sendTime을 LocalDateTime.now()가 아닌 message의 sendTime을 받도록 수정
- 추가적으로 테스트용 화면 사용할 수 있게끔 수정

[bugfix] 몽고db 레포지토리 save 안되는 문제 해결

---

.gitignore
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/EnterCoffeeChatRoomResponse.java

close: #214 
> 시간 관련 데이터는 Z를 붙여 보내기로 하여서 수정
- EnterCoffeeChatRoomResponse의 expirationTime에 @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'") 추가

[bugfix] 채팅방 입장 응답에서 expirationTime에 @JsonFormat 추가

---

domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/coffeechat/entity/MongoMessageType.java

close: #216 
> CODE 타입 메시지를 정상적으로 저장하고 sub에게 보낼 수 있도록 하기 위함
- MongoMessageType에 CODE 추가

[bugfix] MongoMessageType에서 빠져있는 CODE 추가

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/FindReservationResponse.java

close: #221 
> 절대 URL로 보내야는데, 부분 URL로 보내고 있음을 확인했고, 수정하기 위함
- FindReservationResponse에서 imageUrl = reservation.getMember().getImageUrl(); -> imageUrl = ImageUtils.makeImageUrl(reservation.getMember().getImageUrl()); 로 수정하여 응답으로 절대 URL로 보내게 수정

[bugfix] 예약창 상세보기에서 멤버 이미지 URL 깨지는 문제 해결

---

.gitignore
admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/controller/AuthController.java
admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateEmailRequest.java
admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateNicknameRequest.java
admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/LoginRequest.java
admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/SignUpRequest.java
admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/controller/AuthControllerTest.java
admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/dto/AuthRequestDtoTest.java
core/build.gradle
core/src/main/java/com/kernelsquare/core/validation/ValidationGroups.java
core/src/main/java/com/kernelsquare/core/validation/ValidationSequence.java
core/src/main/java/com/kernelsquare/core/validation/constants/AuthValidationConstants.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/controller/AuthController.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/CheckDuplicateEmailRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/CheckDuplicateNicknameRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/SignUpRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberIntroductionRequest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/controller/AuthControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/dto/AuthRequestDtoTest.java

close #223 
백엔드 서버에서 AuthController에서 필요한 유효성 검증 추가
- 회원가입, 로그인, 이메일 중복, 닉네임 중복 검사 시 한글에 대한 유효성 검증을 추가
- 각 항목에 대해 유효성 검증 순서 추가

[hotfix] 회원가입, 로그인, 이메일 중복, 닉네임 중복 체크 시 유효성 검증 순서 및 한글 유효성 검증 추가

---

member-api/src/main/java/com/kernelsquare/memberapi/common/config/SchedulingConfig.java

close: #225 
> 채팅방이 만료되면 비활성화 시키는 스케줄링을 정상적으로 동작시키기 위함
- @EnableScheduling가 달린 SchedulingConfig 추가

[bugfix] 채팅방 비활성화 스케줄링 동작하게끔 SchedulingConfig 추가

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationController.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/AddReservationMemberRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationService.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationServiceTest.java

close: #227 
> 멘토링 가능 날짜 중 첫날에 예약이 안되는 버그를 해결하기 위함
- ReservationArticleService의 !startTime.toLocalDate().isAfter(currentDate.plusDays(7))에서 !startTime.toLocalDate().isAfter(currentDate.plusDays(6))로 수정
- 추가적으로 AddReservationMemberRequest 위치를 service에서 dto로 이동

[bugfix] 멘토링 날짜를 신청하기 누른 날짜로 부터 일주일 뒤부터 가능하게끔 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java

close: #235 
> 멘토가 만드는 커피챗 생성하기에서 예약 가능 날짜가 넘어서 생성이 가능한 버그를 해결하기 위
- ReservationService에서 예약 가능 체크 로직을
(!(startTime.toLocalDate().isAfter(currentDate.plusDays(6)) && startTime.toLocalDate().isBefore(currentDate.plusMonths(1))))로 수정

[bugfix] 멘토가 만드는 커피챗 생성하기에서 예약 가능 날짜가 넘어서 생성 불가하도록 수정

---

domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/reservation/repository/ReservationRepositoryTest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleServiceTest.java

close: #239 
> 예약 생성 기한 체크 로직 (7일 이후, 한달 이전)이 돌아갈 때 LocalDateTime 변환
> 예약 생성 시간 3일 제한 로직 LocalDateTime 변환 및 로직 디버깅
> 관련하여 테스트코드 작성
- 개요를 확인할 것

[bugfix] 예약창 생성 시 예약 일시 체크 로직을 LocalDateTime으로 수정

---

domain-mysql/src/main/resources/db/migration/V2.1__alter_table.sql

- varchar 20에서 100으로 수정
close: #308 
> 에러 로그를 보니 커피챗 글 제목이 20자를 넘으면 채팅방 입장이 안되는 현상을 해결하기 위함
- 플라이웨이 sql를 이용하여 채팅방 이름 길이 제한 수정(varchar 20 -> 100)
- 버전은 V2.1

fix: 비지니스 정책과 채팅방 이름 길이 제한이 안맞는 부분 수정

---

core/src/main/java/com/kernelsquare/core/common_response/error/code/ReservationErrorCode.java
core/src/main/java/com/kernelsquare/core/common_response/service/code/ReservationServiceStatus.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationService.java

close: #317 
> 예약 취소 로직 변경
- 24시간 이전에만 삭제 가능한 로직을
언제든지 삭제 가능하도록 변경
프론트엔드에서 예약 가능기간에는 "취소하시겠습니까?" 라고 뜨고
그 외에는 "패널티" 단어 언급하면서 취소하시겠습니까로 분기처리

[fix] 24시간 미만이 남았더라도 취소는 가능하도록 로직 변경

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/AddReservationMemberRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationServiceTest.java

close: #320 
> 과거시간은 예약 불가하도록 로직 추가
- Requset 변수명 헷갈리지 않게 변경
- 기존에 있던 예약가능한 시간이 아닙니다 에러코드 재활용
- 과거 시간은 예약되지 않게 로직 추가

[fix] 커피챗 과거 시간은 예약되지 않도록 검증하는 로직 추가

---

core/src/main/java/com/kernelsquare/core/constants/SystemConstants.java
domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReaderImpl.java
domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerRepository.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/SchedulerManagerImpl.java

close: #325 
> 현재 답변 랭킹 스케줄러에 모든 답변들 중 상위 3개를 가져오는 것이기 때문에 봇이 단 답변도 포함되는 문제를 해결하기 위함
- answerRepository의 findAnswersByQuestionIdSortedByVoteCount 메서드에서 상위 3개를 가져올 때, answer의 작성자가 봇이 아닌 경우라는 조건을 추가

[bugfix] rankAnswer 스케줄러에 봇이 단 답변 제외하게끔 로직 수정

---

domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/question/entity/Question.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/question/controller/QuestionController.java

close: #326 
> 현재 로직 상 질문 조회시 id로 정렬을 하다보니, id 순 질문 목록과 createdDate 순 질문 목록이 다를 수 있음을 인지하였고, 수정하기 위함
- QuestionController의 findAllQuestions에서 @PageableDefault의 sort를 id에서 createdDate로 변경

[bugfix] 질문 목록 조회 시 생성 날짜 기준으로 내림차순 정렬을 하도록 변경

---

core/src/main/java/com/kernelsquare/core/validation/validator/BadWordValidator.java
domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/reservation_article/entity/ReservationArticle.java
domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/reservation_article/repository/ReservationArticleRepository.java
domain-mysql/src/main/resources/db/migration/V2.4__alter_table.sql
member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerController.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/FindAnswerResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/hashtag/dto/UpdateHashtagRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/UpdateReservationRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/CreateReservationArticleRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/FindAllReservationArticleResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/UpdateReservationArticleRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/controller/ReservationArticleControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/dto/ReservationArticleRequestDtoTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleServiceTest.java

close #330
UI / UX 수정 요청에 따른 API 변경 사항 반영
- ``ReservationArticle`` 에 ``introduction``과 ``end_time`` 컬럼 추가
- ``CreateReservationArticleRequest``, ``UpdateReservationArticleRequest``에 유효성 검증 추가 (비속어 필터링) 및 추가된 엔티티 및 컬럼에 대한 수정할 수 있도록 필드 추가
- ``FindAllReservationArticleResponse`` 값 추가 ( + 멘토의 기존 멘토링 횟수, 이미 마감되거나 시간이 지난 글 보이지 않게 수정, 현재 신청 가능한 예약의 개수, 전체 예약의 개수, 멘토링에 대한 설명 글)
- ``FindAllAnswerResponse`` 에 회원 ID 추가, 답변 프로필 눌렀을 때 회원의 마이 페이지로 이동하기 위함
- ``@BadWordFilter``가 ``String`` 및 ``List<String>`` 을 모두 처리할 수 있도록 내부 구현 수정

[refactor] 멘토링 UI / UX 개선 및 버그 픽스로 인한 API 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaConsumerConfig.java
member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
member-api/src/main/java/com/kernelsquare/memberapi/common/config/RedisConfig.java
member-api/src/main/resources/application.yml

close: #359 
> 추후 무중단 배포가 구현이 된다면 스프링부트 서버는 2개 이상이되고 그 서버들이 하나의 데이터소스를 바라보고 있어야하기 때문에 데이터소스인 Redis, Kafka, MongoDB를 따로 분리하기 위함
- EC2 ubuntu t2.micro 인스턴스를 kernelsquare_datahub의 이름으로 생성
- 서버 접속은 pem 키로만 들어갈 수 있음(pem 키 요청하시면 드리겠습니다.)
- docker로  Redis, Zookeeper, Kafka, MongoDB 설치
- 메모리 부족으로 Kafka 동작하질 않아서 swapfile 8GB 생성
- RedisConfig에 `@Value`으로 받는 url과 port 추가(그에 따라 application.yml에 속성을 추가하여 환경변수 넣음)
- KafkaProducerConfig와 KafkaConsumerConfig에 `@Value`으로 받는 url 추가(그에 따라 application.yml에 속성을 추가하여 환경변수 넣음)
- MONGO_URI 및 MONGO_TEST_URI 환경변수 값 변경(슬랙 참고)
- 로컬에서 연결하여 테스트

[setting] Redis, Kafka, MongoDB를 하나의 서버로 분리

---

member-api/src/main/java/com/kernelsquare/memberapi/common/server/ServerController.java
member-api/src/main/resources/application.yml

close: 
> get-server-information 호출 시 값나오게 수정
- 모듈 명시하면 blue, green 이 나오지 않는 현상 발생
- 모듈 명시 제거하고 local 을 develop 으로 사용하기로 함(VM 옵션 추가해서 local 로 입력)
`-Dspring.profiles.active=local -Dserver.env=develop`
- domain-mysql 의 프로퍼티 값을 ServerController 에서 가져오는 방법을 찾지 못해 member-api application에 dbInfo 추가

[setting] get-server-information 호출 시 값나오게 수정

---

member-api/src/main/resources/application.yml

close: 
> 시크릿 변수 명을 GITHUB 로 시작할 수 없음
- GITHUB_SOCIAL_CLIENT_ID -> SOCIAL_GITHUB_CLIENT_ID
- GITHUB_SOCIAL_CLIENT_SECRET -> SOCIAL_GITHUB_CLIENT_SECRET

[fix] 깃허브 시크릿 변수 이름 변경

---

core/src/main/java/com/kernelsquare/core/common_response/error/code/MemberErrorCode.java
core/src/main/java/com/kernelsquare/core/common_response/service/code/MemberServiceStatus.java
member-api/build.gradle
member-api/src/docs/asciidoc/member-api-index.adoc
member-api/src/docs/asciidoc/member-nickname-updated.adoc
member-api/src/main/java/com/kernelsquare/memberapi/common/config/CorsConfig.java
member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/member/controller/MemberController.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberNicknameRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/member/service/MemberService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/member/controller/MemberControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/member/service/MemberServiceTest.java

close: #431 
> 닉네임 수정 기능 추가
- 닉네임 수정 기능 추가
- 닉네임 중복 체크 로직 추가
- UpdateMemberNicknameRequest 에서 member_id 는 현재 프론트와 admin API 명세서 따라서 작성됨
- 테스트 코드 작성 및 Rest Doc 작성
++ CORS dev 도메인 추가

[feat] 닉네임 변경 기능 추가

---

member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/TokenProviderTest.java

close:
> redis 연결 정보를 하드코딩으로 넣어줌
- 추후 병룡님이 모킹작업 하신다고 함

[fix] TokenProviderTest redis 연결 하드 코딩으로 임시 방편으로 해결

---

member-api/src/main/resources/application.yml

close: #444 
> github oauth2 redirect-uri 수정하여 별칭 도메인을 맞추기 위함
- localhost는 숫자 IP
- localhost -> dev-back.kernelsquare.live

[fix] github oauth2 redirect-uri 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/SchedulerManagerImpl.java
member-api/src/main/resources/templates/chatscreen.html

close: #456 
> 채팅 서버 분리로 인한 만료 메시지 전송 스케줄러 변경이 필요
- 만료 메시지를 채팅 서버와 연결되어있는 kafka로 send하게끔 변경
- 테스트용 화면인 screen.html에서 sockJs 연결 대상을 dev-datahub로 할 수 있게끔 변경

[refactor] 채팅 서버에 만료 메시지를 보낼 수 있게 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java

close: #477 
현재 채팅방 30분 만료 메시지를 member-api에서 카프카로 보내고 있는데, 이 때 카프카 메시지 헤더에 객체 클래스에 대한 정보가 들어있습니다.
그래서 chatting-api 서버의 카프카 컨슈머에서 member-api의 ChatMessageRequest와 같은 위치에서 ChatMessageRequest를 찾으려고 합니다.
하지만 member-api의 ChatMessageRequest와 chatting-api의 ChatMessageRequest 위치가 달라서 찾지못하고 역직렬화에 실패했다는 에러 로그를 출력하게 됩니다.
여기서 카프카의 기본 설정은 역직렬화에 실패한 메시지를 빠른 속도로 다시 역직렬화 시도를 하여 무한루프에 빠지게 됩니다.
그로인해 엄청나게 빠른 속도로 로그가 쌓이고 디스크 공간이 모자르게 됩니다.
- 프로듀서와 컨슈머에서의 위치가 다른 메시지 클래스는 각 config 파일에서 직접 mapping 해주는 방법으로 해결했습니다.
- 채팅 서버의 컨슈머 설정도 변경합니다.

[bugfix] 컨슈머와 프로듀서의 각 위치의 ChatMessageRequest를 인식하기 위한 KafkaProducerConfig 의 JsonSerializer에 ChatMessageRequest 매핑 추가

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/EnterCoffeeChatRoomResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatControllerTest.java

close: #475 
> 입장하기를 할때 CoffeeChatService에서 인메모리에서 관리하는 chatRoomMemberList에 해당 멤버를 추가하는데, 나가기를 할 때 제거하는 로직이 없어서 입장 혹은 재입장할 때마다 chatRoomMemberList에 추가되어 인메모리에 계속 쌓이는 문제가 발생할 것 같아서 chatRoomMemberList를 제거
- CoffeeChatService 파일에서 chatRoomMemberList 제거
- chatRoomMemberList를 사용하는 로직들 수정
- ChatMessageRequest와 ChatMessageResponse 형태는 그대로 둠

refactor: CoffeeChatService에서 인메모리로 관리하는 chatRoomMemberList 제거

---

domain-mongodb/build.gradle
domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/entity/Alert.java
domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/info/AnswerInfo.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/AlertDto.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/CoffeeChatRequestAlertMessage.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/QuestionReplyAlertMessage.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/service/AnswerServiceTest.java

close: #482 
> 화면에 뿌리는데 필요한 데이터는 넣고 불필요한 데이터는 빼고 응답으로 주기 위함
- AlertMessage는 메시지의 멤버 변수는 공통으로 사용하는 것이고 payload는 해당 메시지에만 사용하는 데이터를 넣는 형태로 구현

[refactor] 알림 메시지 데이터 구조 변경

---

domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerRepository.java
domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStore.java
domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStoreImpl.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/SchedulerManagerImpl.java

close: #487
> 랭크 스케줄러를 돌리면 랭킹 매긴 답변들의 modify 가 변경되면서 화면에 (수정됨) 으로 표시됨
- 랭크 스케줄러로 인해 답변이 (수정됨) 으로 바뀌는 현상 -> 엔티티 타지 않고 바로 repository 로 update

[refactor] 랭크 스케줄러 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerController.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/facade/ChatGptFacade.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptService.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptServiceImpl.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java

close: #492 
> chatGPT가 답변을 달 때도 질문 작성자에게 알림이 가도록 수정하기 위해 chatGptService와 alertService를 사용하는 chatGptFacade를 만들어 anaswer 컨트롤러에 사용
- 기존 AnswerInfo와 AlertDtoMapper를 사용하여 코드 구현

[refactor] chatGPT가 답변을 달 때도 질문 작성자에게 알림이 가도록 수정
