Kernel360/f1-KernelSquare-backend

.github/workflows/gradle.yml
appspec.yml
scripts/deploy.sh

close: #3 
> 자동 배포
- 자동 배포를 위한 스크립트 작성

[setting] 배포 환경 세팅

---

.github/workflows/gradle.yml

close: #3 
> 수동 배포를 위한 CD 주석처리
- 자동 배포 - S3 올라가는 거 확인, CodeDeploy 성공 확인, EC2 프로젝트 파일 및 jar 생성 확인
-> 수동 배포를 위한 CD 주석처리

[setting] 자동 배포 -> 수동 배포 환경 세팅

---

src/main/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerController.java
src/main/java/com/kernel360/kernelsquare/domain/answer/dto/UpdateAnswerRequest.java
src/main/java/com/kernel360/kernelsquare/domain/answer/entity/Answer.java
src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/AnswerErrorCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java

close: #19
close: #20 
> 답변 수정 & 삭제기능 추가
- 해당 기능에 대하여 API 명세를 준수하여 작성하였음
- Answer가 존재하지 않는 경우 호출되는 에러 코드 생성

[feat] 답변 수정 & 삭제

---

.github/CODEOWNERS

[env]CODEOWNERS 파일 추가

---

src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java

#32 
> 응답코드 수정
- LEVEL NOT FOUND : 1400
- LEVEL ALREADY EXISTED : 1401
- LEVEL CREATED : 1440

등급 생성 응답코드 수정

---

src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/CreateTechStackResponse.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/FindAllTechStacksResponse.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/TechStackResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TechStackServiceStatus.java
src/test/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepositoryTest.java
src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java

close: #26 
> 기술 스택 모든 조회 기능을 구현하기 위함
- 단일 조회는 없음
- 현재 응답 메시지의 data는 기술 스택 이름만 List 형식으로 보내줌
- 추가적으로 service와 controller test 코드 스타일 수정(확인해주시고 의견이 있으시면 주세요)

[feat] 기술 스택 모든 조회 기능 개발

---

src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/UpdateTechStackRequest.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/TechStackResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TechStackServiceStatus.java
src/test/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java

close: #40 
> 기술 스택 수정 기능을 구현하기 위함
- 추가적으로 기술 스택 모든 조회 응답에 기술 이름 뿐만 아니라 해당 기술에 대한 모든 정보를 넣음

[feat] 기술 스택 수정 기능 개발

---

src/main/java/com/kernel360/kernelsquare/domain/level/controller/LevelController.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelResponse.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/FindAllLevelResponse.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/LevelDto.java
src/main/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepository.java
src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/LevelResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java

close: #34 
> 등급 조회
- 등급 조회는 단건이 아닌 리스트로 모두 가져옵니다
- response 형식을 levels 로 한번 더 감쌌습니다.

[feat] 등급 조회 기능

---

src/main/java/com/kernel360/kernelsquare/domain/answer/entity/Answer.java
src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
src/main/java/com/kernel360/kernelsquare/domain/question/controller/QuestionController.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionResponse.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
src/main/java/com/kernel360/kernelsquare/domain/question/entity/Question.java
src/main/java/com/kernel360/kernelsquare/domain/question/service/QuestionService.java
src/main/java/com/kernel360/kernelsquare/global/dto/Pagination.java
src/test/java/com/kernel360/kernelsquare/domain/question/controller/QuestionControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
src/test/java/com/kernel360/kernelsquare/domain/question_tech_stack/repository/QuestionTechStackRepositoryTest.java

close: #43 
> 질문 상세 조회에서 답변 리스트도 응답에 보내기 위함 및 변경된 컨벤션에 따른 리팩토링
- 질문 상세 조회에서 답변 리스트를 불러오는 코드를 그대로 가져옴
- 테스트 코드 수정
- 질문 모든 조회 페이지네이션 빌더패턴 부분 pagenation dto 안에 toEntitiy로 정의하여 사용

[refactor] 질문 관련 코드들 리팩토링

---

src/main/java/com/kernel360/kernelsquare/domain/level/controller/LevelController.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/DeleteLevelRequest.java
src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/LevelResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java

close: #35 
> 등급 삭제
- 등급 삭제 기능 구현

[feat] 레벨 삭제 기능

---

src/main/java/com/kernel360/kernelsquare/domain/level/controller/LevelController.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelResponse.java
src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/CommonErrorCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/LevelResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CommonServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java

close: #33 
> 등급 수정
- 등급 수정 기능
- Request 할 때 바뀌지 않는 값은 프론트에서 넣어서 줍니다
예를 들어 name 만 바뀐다고 할 시 imageUrl 에는 기존 imageUrl 넣어서 요청

[feat] 등급 수정 기능

---

src/main/java/com/kernel360/kernelsquare/domain/answer/dto/CreateAnswerRequest.java
src/main/java/com/kernel360/kernelsquare/domain/answer/dto/UpdateAnswerRequest.java
src/main/java/com/kernel360/kernelsquare/domain/auth/controller/AuthController.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateEmailRequest.java
src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateNicknameRequest.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelRequest.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelResponse.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/dto/CreateMemberAnswerVoteRequest.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/CreateTechStackRequest.java
src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/UpdateTechStackRequest.java
src/main/java/com/kernel360/kernelsquare/global/common_response/ApiResponse.java
src/main/java/com/kernel360/kernelsquare/global/common_response/ResponseEntityFactory.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/TokenErrorCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AuthorityServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CommonServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TokenServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/config/CorsConfig.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/main/java/com/kernel360/kernelsquare/global/constants/FilterHttpMethodConstants.java
src/main/java/com/kernel360/kernelsquare/global/filter/JWTTokenSettingFilter.java
src/main/java/com/kernel360/kernelsquare/global/jwt/TokenProvider.java
src/main/java/com/kernel360/kernelsquare/global/util/ExceptionMessageConverter.java
src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java

[refactor] security API Endpoint / CORS 수정 / Valid annotation 예외 처리 추가

---

build.gradle
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/main/resources/application.yml

close: #76 , #77 
> 모니터링 환경 세팅
- 모니터링 환경 세팅을 위한 프로메테우스, 그라파나 세팅

[setting] 모니터링 환경 세팅

---

src/main/java/com/kernel360/kernelsquare/global/aop/Logging.java
src/main/java/com/kernel360/kernelsquare/global/aop/MDCFilter.java
src/main/resources/application.yml
src/main/resources/logback.xml

close: #16
> aop 리팩터링
- 모든 컨트롤러, 서비스에 적용
- 레파지토리는 제외
- MDC 적용하여 트래킹 쉽게 만듬

[refactor] AOP 리팩터링 1차

---

src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelRequest.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/LevelDto.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelResponse.java
src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/main/resources/data.sql
src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java

close: #97 
> Level 테이블에 levelUpperLimit 컬럼 추가로 인한 Level 로직 리팩토링
- 1차 완료
- data.sql에 postman 테스트를 위한 데이터 추가
- 추가적으로 필요없는 내용 삭제

[refactor] Level 로직 리팩토링

---

src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAnswerResponse.java
src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/entity/MemberAnswerVote.java
src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/repository/MemberAnswerVoteRepository.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java

close: #60 
> 답변 조회시 작성자의 레벨
> 조회자의 투표 여부 확인
- 비회원의 경우 vote_count : 0
- 회원의 경우 vote_count : -1 or 0 or 1

[feat] 답변 전체 조회시 작성자 레벨과 조회자 투표 여부 추가

---

build.gradle
src/main/resources/application.yml
src/main/resources/db/migration/V1.0__init_table.sql
src/main/resources/db/migration/V1.1__add_initial_data.sql
src/test/resources/application.yml

close: #99 #93 
> flyway을 통해 DB 관리를 하기 위함
- 기존에 있던 data.sql로 초기 데이터를 넣는 과정을 flyway에 추가
- 현재 테스트 DB에는 flyway를 적용하지 않음

[setting] flyway 적용

---

src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatController.java
src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CreateCoffeeChatRoomRequest.java
src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CreateCoffeeChatRoomResponse.java
src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CreateRoomRequest.java
src/main/java/com/kernel360/kernelsquare/domain/coffeechat/entity/ChatRoom.java
src/main/java/com/kernel360/kernelsquare/domain/coffeechat/repository/CoffeeChatRepository.java
src/main/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatService.java
src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/CoffeeChatResponseCode.java
src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CoffeeChatServiceStatus.java
src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
src/main/resources/db/migration/V1.3__add_table.sql
src/test/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CoffeeChatRequestDtoTest.java
src/test/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatServiceTest.java

close: #115 
> 멘토가 채팅방을 생성하는 기능을 구현하기 위함
- 채팅방을 생성할 때 요청과 응답 dto 멤버 변수는 임의로 설정 했습니다.
- 채팅방에 대한 정보는 DB에 저장됩니다.

[feat] 채팅방 생성 기능 개발

---

src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CreateCoffeeChatRoomRequest.java
src/main/java/com/kernel360/kernelsquare/domain/coffeechat/entity/ChatRoom.java
src/main/java/com/kernel360/kernelsquare/domain/reservation/entity/Reservation.java
src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
src/main/resources/application.yml
src/main/resources/db/migration/V1.2__add_initial_data.sql
src/main/resources/db/migration/V1.3__add_table.sql
src/test/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatControllerTest.java
src/test/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatServiceTest.java
src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java

close: #85 
> 예약창 생성 로직 리팩터링
- 예약창 생성 시 hashtag, chatroom, reservation 동시에 생성
- Flyway 컬럼 및 데이터 추가
- 테스트 확인 완료

[refactor] 예약창 생성 로직 리팩터링

---

.github/workflows/cr.yml

ChatGPT 코드 리뷰 관련 cr.yml 생성

---

src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/ScreenController.java
src/main/resources/templates/chat/screen.html

close: #133 
> 우분투, 맥, 윈도우 환경에서 다 돌아가는 코드로 수정하기 위함
- 우분투, 맥, 윈도우 환경에서 정상 동작함을 확인함

[refactor] 타임리프 관련 코드 수정

---

.github/workflows/gradle.yml

[refactor] 각 모듈 application.yml 값 할당하기 위한 수정

---

admin-api/build.gradle
member-api/build.gradle

close: #180 
> 멀티 모듈 asciidoctor 관련 빌드가 안되는 문제를 해결하기 위함
- id 'org.asciidoctor.convert' version '1.5.9.2' 를 id 'org.asciidoctor.jvm.convert' version '3.3.2' 로 변경

[bugfix] asciidoctor 관련 문제 해결

---

domain-mysql/src/main/resources/db/migration/V1.8__alter_table.sql

> SQL 에러로 컬럼 수정
- date -> time 으로 수정

[bugfix] chatroom column mismatch 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaConsumerConfig.java
member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
member-api/src/main/java/com/kernelsquare/memberapi/common/util/ChatMessageConverter.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/FindAnswerResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/MessageController.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessage.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/FindChatHistoryResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/FindMongoChatMessage.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/KafkaService.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/FindQuestionResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/FindReservationResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/FindAllReservationArticleResponse.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/FindReservationArticleResponse.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/TestMessageController.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatServiceTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/socket/StompSocketTest.java

close: #205 
> 프론트 서버에서 LocalDateTime 형식이 UTC임을 인식하게 하기 위함
- 현재 실시간 채팅 메시지는 request와 response 둘다 어노테이션이 달려있음

[refactor] 응답으로 보내는 DTO에서 시간과 관련된 멤버 변수에 JsonFormat 어노테이션 달기

---

admin-api/src/main/resources/logback.xml
member-api/src/main/resources/logback.xml

> 각 API 모듈의 로그백 파일 추가
- 모든 레벨에서 로그 기록 이후 수립된 정책에 따라 설정 변경

[chore] 로그백 설정 추가

---

core/src/main/java/com/kernelsquare/core/common_response/error/exception/BusinessException.java

close: #226 
> error레벨 로그에서도 어떤 예외 메시지인지 남기기 위함
- BusinessException 생성자에 super(errorCode.getMsg()) 추가

[bugfix] error레벨 로그에 exception message에 메시지 내용을 넣을 수 있게 수정

---

member-api/src/test/java/com/kernelsquare/memberapi/domain/hashtag/controller/HashtagControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/hashtag/service/HashtagServiceTest.java

close: #263 
> 해시태그 테스트 코드에서 # 삭제
- 컨트롤러 테스트, 서비스 테스트 코드에서 해시태그 content 내용 중 "#" 부분 제거
- "#" 은 프론트에서 붙히고 떼고 하기로 정해짐

[chore] 해시태그 테스트 # 삭제

---

core/src/main/java/com/kernelsquare/core/common_response/error/code/AnswerErrorCode.java
core/src/main/java/com/kernelsquare/core/common_response/response/code/AnswerResponseCode.java
core/src/main/java/com/kernelsquare/core/common_response/service/code/AnswerServiceStatus.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/service/AnswerService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/service/AnswerServiceTest.java

close: #265 
> 본인 질문 글에 답변 불가
- 본인이 작성한 질문글에는 답변을 달 수 없는 정책으로 로직 추가하였습니다.

[bugfix] 본인 질문 글에 답변 불가

---

core/src/main/java/com/kernelsquare/core/common_response/error/code/QuestionErrorCode.java
core/src/main/java/com/kernelsquare/core/common_response/service/code/QuestionServiceStatus.java
domain-mysql/src/main/resources/db/migration/V1.9__alter_table.sql
member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/CreateAnswerRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/UpdateAnswerRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberIntroductionRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/CreateQuestionRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/UpdateQuestionRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/CreateReservationArticleRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/UpdateReservationArticleRequest.java
member-api/src/main/java/com/kernelsquare/memberapi/domain/search/service/SearchService.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/dto/AnswerRequestDtoTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/member/dto/MemberRequestDtoTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/question/controller/QuestionControllerTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/question/dto/QuestionRequestDtoTest.java
member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/dto/ReservationArticleRequestDtoTest.java

close: #246
close: #250 
close: #252   
> 텍스트 사이즈 검증 추가
마크다운 컨텐츠 글자수 상한 제한
- 질문 (10자, 10000자)
- 답변 (10자, 10000자) 
- 마이페이지 자기소개 (10자, 1000자)
- 예약창 (10자, 1000자)
- 질문제목(5자, 100자)
- 예약창제목(5자, 100자)
- 검색창(150자)
- 공지제목(5자, 100자)
- 공지내용(10자, 10000자)

[bugfix] 텍스트 사이즈 Valid 추가 및 테스트 코드

---

.github/workflows/release.yml

[setting] release setting - add yml

---

domain-mysql/src/main/resources/db/migration/V2.5__add_table.sql

fix: flyway 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting_comment/dto/CodingMeetingCommentDto.java

close: #361
> 업데이트된 에러 메시지가 Main Branch에는 반영이 되어있지 않은 점 수정
- Main 브랜치에 바로 merge하여 수동배포하겠습니다

[fix] 모각코 댓글 에러메시지 수정

---

member-api/src/main/java/com/kernelsquare/memberapi/common/server/ServerController.java

close: #365 
> 모듈 명시
-  VM 옵션으로 prod1 혹은 pord2 지정했을 때는 문제없이 돌아가나 local 로 돌렸을 때(즉, 지정하지 않았을 때) serverName 을 못찾는 이슈발생하여 모듈을 명시함 해결

[setting] ServerController @Value 모듈 명시

---

member-api/src/main/java/com/kernelsquare/memberapi/common/server/ServerController.java
member-api/src/main/resources/application.yml

close:
> local 일 때 port 지정
- 기존 개발 환경과 동일하게 8501 유지
- ServerController 에서 env @Value 는 모듈 명시 제외

[setting] develop port 지정

---

.github/workflows/cd.yml

[setting] 무중단 배포를 위한 cd 워크플로우 수정

---

.github/workflows/cd.yml

[setting] 무중단 배포를 위한 cd 워크플로우 수정 2차

---

.github/workflows/cd.yml

[merge] develop into main

---

.github/workflows/cd.yml

[setting] 무중단 배포를 위한 cd 워크플로우 수정 3차

---

.github/workflows/cd.yml
member-api/Dockerfile

setting: 무중단 배포를 위한 cd 워크플로우 수정 4차

---

member-api/src/main/resources/application.yml

#424 
> yml 수정
- tempo 세팅을 위한 yml 수정

[settin] tempo 세팅을 위한 yml 수정

---

member-api/build.gradle
member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/CustomInMemoryOAuth2AuthorizedClientService.java

close: #441 
- develop 서버에서 api 명세가 접속되지 않던 문제 해결

[fix] Spring REST Docs build.gradle 수정 #441

---

.github/workflows/cd-dev.yml
.github/workflows/ci.yml
domain-mysql/src/test/resources/application.yml

close: #436 
> develop 브랜치에 merge가 됬을 때 dev 인스턴스 서버에 자동 배포가 되도록 cd-dev 워크플로우 작성
- 관리자 인스턴스 서버의 cd와 유사하게 작성

[setting] develop 브랜치에 merge가 됬을 때 dev 인스턴스 서버에 자동 배포가 되도록 cd-dev 워크플로우 작성

---

.github/workflows/cd-dev.yml

close: #444 
> run과 uses 분리
- run과 uses를 같은 레벨에서 같이 못씀

fix: cd-dev 잘못된 부분 수정

---

.github/workflows/cd-dev.yml

close: #444 
> cd-dev 잘못된 부분 수정하기 위함
- docker build와 ssh 인스턴스에서 실행 시키는 방법 수정

fix: cd-dev 잘못된 부분 수정 2차

---

.github/workflows/cd-dev.yml

close: #444 
> cd-dev 잘못된 부분 수정을 하기 위함
- 시크릿값에서 EC2_USERNAME이 아닌 EC2_USER임

fix: cd-dev 잘못된 부분 수정 3차

---

.github/workflows/cd-dev.yml

close: #444
> ssh 접속이 실패하는 문제를 해결하기 위함 
- EC2_USER -> DEV_SSH_USER

fix: cd-dev 잘못된 부분 수정 4차

---

member-api/src/main/resources/application.yml

close: #444 
> 대성님 요청으로 리다이렉트 주소 변경하기 위함
- 별칭대신 숫자 IP 직접 입력

fix: 대성님 요청으로 리다이렉트 주소 변경

---

member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginFailureHandler.java
member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java

> dev 소셜로그인
- 주소 미스매치로 수정함
- http://dev.kernelsquare.live/oauth/github

[fix] 소셜로그인 리다이렉트 주소 변경

---

member-api/src/main/resources/application.yml

[fix] 소셜로그인 리다이렉트 주소 변경2

---

member-api/src/main/resources/application.yml

fix: 소셜로그인 리다이렉트 주소 변경3

---

member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java

[fix] 소셜로그인 리다이렉트 주소 변경4

---

member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java

fix: 소셜로그인 리다이렉트 주소 변경5

---

member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java

fix: 소셜로그인 리다이렉트 주소 변경6

---

member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java

fix: 소셜로그인 리다이렉트 주소 변경7

---

member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginFailureHandler.java
member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java
member-api/src/main/resources/application.yml

close: #467 
> 메인에 맞게 설정
- Value 값으로 dev, main 분류
- 위와 같이 yml 파일 수정

[feat] 소셜로그인 메인 반영

---

member-api/src/main/resources/application.yml

[fix] redirectURL 변경

---

member-api/src/main/resources/application.yml

close: #489 
> requests 를 가지고 오지 못함
- requests 를 가지고 오도록 추가

[Infra] application.yml 에서 management 부분 수정 및 추가

---

member-api/src/main/resources/application.yml

[fix] '' 추가

---

README.md

프로젝트 리드미 정리 1차

---

README.md

프로젝트 리드미 2차  수정

---

README.md

리드미 3차 - nginx 추가
